import { useTranslation } from 'next-i18next';
export default () => {
  const { t } = useTranslation('admin');
  return {
    yes: t('yes'),
    no: t('no'),
    all: t('All'),
    equals: t('equals'),
    in: t('in'),
    notIn: t('notIn'),
    lt: t('lt'),
    lte: t('lte'),
    gt: t('gt'),
    gte: t('gte'),
    not: t('not'),
    contains: t('contains'),
    startsWith: t('startsWith'),
    endsWith: t('endsWith'),
    addFilter: t('addFilter'),
    nonFilterMsg:
      t('nonFilterMsg'),
    deleteConfirm: t('deleteConfirm'),
    select: t('select'),
    actions: t('actions'),
    relation: t('relation'),
    viewAll: t('viewAll'),
    viewRelated: t('viewRelated'),
    connected: t('connected'),
    connect: t('connect'),
    disConnect: t('disConnect'),
    editRow: t('editRow'),
    viewRow: t('viewRow'),
    deleteRow: t('deleteRow'),
    showing: t('showing'),
    of: t('of'),
    results: t('results'),
    goToFirstPage: t('goToFirstPage'),
    goToLastPage: t('goToLastPage'),
    goPageNumber: t('goPageNumber'),
    setPageSize: t('setPageSize'),
    filter: t('filter'),
    save: t('save'),
    cancel: t('cancel'),
    close: t('close'),
    create: t('create'),
    update: t('update'),
    view: t('view'),
    isRequired: t('isRequired'),
    show: t('show'),
  };
};
