const form = {
  name: 'Social',
  intl: {
    titleId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._Title',
    title: 'Social',
    descriptionId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._Description',
    description: 'Social Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 5,
  formFields: [
    {
      name: 'url',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.url._Title',
        title: 'url',
        descriptionId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.url._Description',
        description: 'url Description',
      },
    },
    {
      name: 'igId',
      custom: null,
      order: 2,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.igId._Title',
        title: 'igId',
        descriptionId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.igId._Description',
        description: 'igId Description',
      },
    },
    {
      name: 'lineId',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.lineId._Title',
        title: 'lineId',
        descriptionId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.lineId._Description',
        description: 'lineId Description',
      },
    },
    {
      name: 'tgId',
      custom: null,
      order: 4,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.tgId._Title',
        title: 'tgId',
        descriptionId: '_Admin.Website._PageGroup.Request._Page.Affiliate._Form.Social._FormField.tgId._Description',
        description: 'tgId Description',
      },
    },
  ],
};
export default form;
