const form = {
  name: 'Description',
  intl: {
    titleId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._Title',
    title: 'Description',
    descriptionId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._Description',
    description: 'Description Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 1,
  formFields: [
    {
      name: 'email',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.email._Title',
        title: 'email',
        descriptionId:
          '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.email._Description',
        description: 'email Description',
      },
    },
    {
      name: 'walletAddress',
      custom: null,
      order: 2,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.walletAddress._Title',
        title: 'walletAddress',
        descriptionId:
          '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.walletAddress._Description',
        description: 'walletAddress Description',
      },
    },
    {
      name: 'id',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.id._Title',
        title: 'id',
        descriptionId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.id._Description',
        description: 'id Description',
      },
    },
    {
      name: 'createdAt',
      custom: null,
      order: 4,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'DateTime',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.createdAt._Title',
        title: 'createdAt',
        descriptionId:
          '_Admin.Website._PageGroup.Customer._Page.Customer._Form.Description._FormField.createdAt._Description',
        description: 'createdAt Description',
      },
    },
  ],
};
export default form;
