const form = {
  name: 'Adverstisement',
  intl: {
    titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._Title',
    title: 'Adverstisement',
    descriptionId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._Description',
    description: 'Adverstisement Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 5,
  formFields: [
    {
      name: 'name',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.name._Title',
        title: 'name',
        descriptionId:
          '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.name._Description',
        description: 'name Description',
      },
    },
    {
      name: 'description',
      custom: null,
      order: 2,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.description._Title',
        title: 'description',
        descriptionId:
          '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.description._Description',
        description: 'description Description',
      },
    },
    {
      name: 'url',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.url._Title',
        title: 'url',
        descriptionId:
          '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.url._Description',
        description: 'url Description',
      },
    },
    {
      name: 'imageObj',
      custom: null,
      order: 4,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Json',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.imageObj._Title',
        title: 'imageObj',
        descriptionId:
          '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.imageObj._Description',
        description: 'imageObj Description',
      },
    },
    {
      name: 'days',
      custom: null,
      order: 5,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Int',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.days._Title',
        title: 'days',
        descriptionId:
          '_Admin.Website._PageGroup.Request._Page.Request._Form.Adverstisement._FormField.days._Description',
        description: 'days Description',
      },
    },
  ],
};
export default form;
