const form = {
  name: 'Details',
  intl: {
    titleId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._Title',
    title: 'Details',
    descriptionId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._Description',
    description: 'Details Description',
  },
  hideOn: null,
  order: 3,
  formFields: [
    {
      name: 'days',
      custom: null,
      order: 100,
      hideOn: null,
      fullWidth: true,
      inlineEdit: null,
      intl: {
        titleId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.days._Title',
        title: 'days',
        descriptionId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.days._Description',
        description: 'days Description',
      },
    },
    {
      name: 'description',
      custom: null,
      order: 100,
      hideOn: null,
      fullWidth: true,
      inlineEdit: null,
      intl: {
        titleId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.description._Title',
        title: 'description',
        descriptionId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.description._Description',
        description: 'description Description',
      },
    },
    {
      name: 'imageObj',
      custom: null,
      order: 100,
      hideOn: null,
      fullWidth: true,
      inlineEdit: null,
      intl: {
        titleId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.imageObj._Title',
        title: 'imageObj',
        descriptionId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.imageObj._Description',
        description: 'imageObj Description',
      },
    },
    {
      name: 'name',
      custom: null,
      order: 100,
      hideOn: null,
      fullWidth: true,
      inlineEdit: null,
      intl: {
        titleId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.name._Title',
        title: 'name',
        descriptionId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.name._Description',
        description: 'name Description',
      },
    },
    {
      name: 'url',
      custom: null,
      order: 100,
      hideOn: null,
      fullWidth: true,
      inlineEdit: null,
      intl: {
        titleId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.url._Title',
        title: 'url',
        descriptionId: '_Admin.User._PageGroup.Request._Page.Request._Form.Details._FormField.url._Description',
        description: 'url Description',
      },
    },
  ],
};
export default form;
