const form = {
  name: 'Message',
  intl: {
    titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._Title',
    title: 'Message',
    descriptionId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._Description',
    description: 'Message Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 4,
  formFields: [
    {
      name: 'subject',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._FormField.subject._Title',
        title: 'subject',
        descriptionId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._FormField.subject._Description',
        description: 'subject Description',
      },
    },
    {
      name: 'message',
      custom: null,
      order: 2,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._FormField.message._Title',
        title: 'message',
        descriptionId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._FormField.message._Description',
        description: 'message Description',
      },
    },
    {
      name: 'createdAt',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'DateTime',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._FormField.createdAt._Title',
        title: 'createdAt',
        descriptionId:
          '_Admin.Website._PageGroup.Request._Page.Request._Form.Message._FormField.createdAt._Description',
        description: 'createdAt Description',
      },
    },
  ],
};
export default form;
