const form = {
  name: 'OrderTotal',
  intl: {
    titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._Title',
    title: 'OrderTotal',
    descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._Description',
    description: 'OrderTotal Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 4,
  formFields: [
    {
      name: 'discount',
      custom: null,
      order: 100,
      hideOn: { field: { name: 'discount', operator: '===', value: null } },
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Float',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.discount._Title',
        title: 'discount',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.discount._Description',
        description: 'discount Description',
      },
    },
    {
      name: 'amount',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Float',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.amount._Title',
        title: 'amount',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.amount._Description',
        description: 'amount Description',
      },
    },
    {
      name: 'affiliateFee',
      custom: null,
      order: 2,
      hideOn: { field: { name: 'affiliateFee', operator: '===', value: null } },
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Float',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.affiliateFee._Title',
        title: 'affiliateFee',
        descriptionId:
          '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.affiliateFee._Description',
        description: 'affiliateFee Description',
      },
    },
    {
      name: 'stripeFee',
      custom: null,
      order: 2,
      hideOn: { field: { name: 'paymentType', operator: '!==', value: 'stripe' } },
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Boolean',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.stripeFee._Title',
        title: 'stripeFee',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.stripeFee._Description',
        description: 'stripeFee Description',
      },
    },
    {
      name: 'applicationFee',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Float',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.applicationFee._Title',
        title: 'applicationFee',
        descriptionId:
          '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.applicationFee._Description',
        description: 'applicationFee Description',
      },
    },
    {
      name: 'total',
      custom: null,
      order: 4,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Float',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.total._Title',
        title: 'total',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.OrderTotal._FormField.total._Description',
        description: 'total Description',
      },
    },
  ],
};
export default form;
