const form = {
  name: 'Tracking',
  intl: {
    titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._Title',
    title: 'Tracking',
    descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._Description',
    description: 'Tracking Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 1,
  formFields: [
    {
      name: 'id',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._FormField.id._Title',
        title: 'id',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._FormField.id._Description',
        description: 'id Description',
      },
    },
    {
      name: 'paid',
      custom: null,
      order: 2,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Boolean',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._FormField.paid._Title',
        title: 'paid',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._FormField.paid._Description',
        description: 'paid Description',
      },
    },
    {
      name: 'createdAt',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'DateTime',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._FormField.createdAt._Title',
        title: 'createdAt',
        descriptionId: '_Admin.Website._PageGroup.Order._Page.Order._Form.Tracking._FormField.createdAt._Description',
        description: 'createdAt Description',
      },
    },
  ],
};
export default form;
