const form = {
  name: 'Basic',
  intl: {
    titleId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._Title',
    title: 'Basic',
    descriptionId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._Description',
    description: 'Basic Description',
  },
  app: null,
  hideOn: null,
  disableOn: null,
  order: 2,
  formFields: [
    {
      name: 'name',
      custom: null,
      order: 1,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._FormField.name._Title',
        title: 'name',
        descriptionId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._FormField.name._Description',
        description: 'name Description',
      },
    },
    {
      name: 'description',
      custom: null,
      order: 2,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._FormField.description._Title',
        title: 'description',
        descriptionId:
          '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._FormField.description._Description',
        description: 'description Description',
      },
    },
    {
      name: 'createdAt',
      custom: null,
      order: 3,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'DateTime',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._FormField.createdAt._Title',
        title: 'createdAt',
        descriptionId: '_Admin.Website._PageGroup.Media._Page.Attachment._Form.Basic._FormField.createdAt._Description',
        description: 'createdAt Description',
      },
    },
  ],
};
export default form;
