const form = {
  name: 'PageHiddenFields',
  intl: {
    titleId: '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._Title',
    title: 'PageHiddenFields',
    descriptionId: '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._Description',
    description: 'PageHiddenFields Description',
  },
  app: null,
  hideOn: { action: 'all' },
  disableOn: null,
  order: 8,
  formFields: [
    {
      name: 'externalUrl',
      custom: null,
      order: 100,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._FormField.externalUrl._Title',
        title: 'externalUrl',
        descriptionId:
          '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._FormField.externalUrl._Description',
        description: 'externalUrl Description',
      },
    },
    {
      name: 'isExternalLink',
      custom: null,
      order: 100,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'Boolean',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._FormField.isExternalLink._Title',
        title: 'isExternalLink',
        descriptionId:
          '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._FormField.isExternalLink._Description',
        description: 'isExternalLink Description',
      },
    },
    {
      name: 'slug',
      custom: null,
      order: 100,
      hideOn: null,
      disableOn: null,
      requiredOn: null,
      fullWidth: true,
      inlineEdit: null,
      type: 'String',
      link: null,
      defaultValue: null,
      intl: {
        titleId: '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._FormField.slug._Title',
        title: 'slug',
        descriptionId: '_Admin.Website._PageGroup.Media._Page.Page._Form.PageHiddenFields._FormField.slug._Description',
        description: 'slug Description',
      },
    },
  ],
};
export default form;
